# Generated by Django 6.0 on 2026-01-26 13:35

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', api.models.CustomUserManager()),
            ],
        ),
    ]
